# Generated by Django 3.2.4 on 2021-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='Jain', max_length=100),
            preserve_default=False,
        ),
    ]
